[workspace]
resolver="2"

members = [
    "mutiny-core",
    "mutiny-wasm",
]


# Tell `rustc` to optimize for small code size.
[profile.release.package.mutiny-core]
opt-level = "s"

[profile.release.package.mutiny-wasm]
opt-level = "s"
